# Generated by Django 4.0.4 on 2022-06-09 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0002_makerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='cat',
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='e_mail',
            field=models.EmailField(blank=True, db_index=True, max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='makerequest',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Подкатегория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='photographer.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегории',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='photos',
            name='subcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='photographer.subcategory', verbose_name='Подкатегория'),
        ),
    ]
