# Generated by Django 4.0.4 on 2022-06-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0003_remove_photos_cat_alter_makerequest_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='photo',
            field=models.ImageField(null=True, upload_to='subcategory_photos/%Y/%m/%d/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
