# Generated by Django 4.0.4 on 2022-07-07 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0004_subcategory_photo_alter_photos_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Описание')),
                ('photo1', models.ImageField(null=True, upload_to='blog_photos/%Y/%m/%d/', verbose_name='Фото 1 (обложка)')),
                ('photo2', models.ImageField(null=True, upload_to='blog_photos/%Y/%m/%d/', verbose_name='Фото 2')),
                ('photo3', models.ImageField(null=True, upload_to='blog_photos/%Y/%m/%d/', verbose_name='Фото 3')),
                ('photo4', models.ImageField(null=True, upload_to='blog_photos/%Y/%m/%d/', verbose_name='Фото 4')),
                ('photo5', models.ImageField(null=True, upload_to='blog_photos/%Y/%m/%d/', verbose_name='Фото 5')),
                ('photo6', models.ImageField(null=True, upload_to='blog_photos/%Y/%m/%d/', verbose_name='Фото 6')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
            ],
            options={
                'verbose_name': 'Статьи',
                'verbose_name_plural': 'Статьи',
                'ordering': ['time_create', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub', to='photographer.category', verbose_name='Категория'),
        ),
    ]
