# Generated by Django 4.0.4 on 2022-07-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0006_alter_blog_photo2_alter_blog_photo3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Описание')),
                ('photo1', models.ImageField(null=True, upload_to='promo_photos/%Y/%m/%d/', verbose_name='Фото 1 (обложка)')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='promo_photos/%Y/%m/%d/', verbose_name='Фото 2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='promo_photos/%Y/%m/%d/', verbose_name='Фото 3')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='promo_photos/%Y/%m/%d/', verbose_name='Фото 4')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='promo_photos/%Y/%m/%d/', verbose_name='Фото 5')),
                ('photo6', models.ImageField(blank=True, null=True, upload_to='promo_photos/%Y/%m/%d/', verbose_name='Фото 6')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
            ],
            options={
                'verbose_name': 'Акции',
                'verbose_name_plural': 'Акции',
                'ordering': ['-date_start', 'title'],
            },
        ),
    ]
