# Generated by Django 4.0.4 on 2022-07-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0007_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(null=True, upload_to='gift_photos/%Y/%m/%d/', verbose_name='Фото (обложка)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
        ),
    ]
