# Generated by Django 4.0.4 on 2022-07-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0009_alter_gift_options_gift_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='inst_slider/%Y/%m/%d/', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Фото для инста-слайдера',
                'verbose_name_plural': 'Фото для инста-слайдера',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='main_slider/%Y/%m/%d/', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Фото для главного слайдера',
                'verbose_name_plural': 'Фото для главного слайдера',
                'ordering': ['name'],
            },
        ),
    ]
