# Generated by Django 4.0.4 on 2022-07-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0010_instslider_mainslider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instslider',
            options={'ordering': ['id'], 'verbose_name': 'Фото для инста-слайдера', 'verbose_name_plural': 'Фото для инста-слайдера'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='content1',
            field=models.TextField(null=True, verbose_name='Инфа1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='content2',
            field=models.TextField(blank=True, verbose_name='Инфа2'),
        ),
        migrations.AddField(
            model_name='blog',
            name='content3',
            field=models.TextField(blank=True, verbose_name='Инфа3'),
        ),
        migrations.AddField(
            model_name='blog',
            name='content4',
            field=models.TextField(blank=True, verbose_name='Инфа4'),
        ),
        migrations.AddField(
            model_name='blog',
            name='content5',
            field=models.TextField(blank=True, verbose_name='Инфа5'),
        ),
        migrations.AddField(
            model_name='blog',
            name='content6',
            field=models.TextField(blank=True, verbose_name='Инфа6'),
        ),
        migrations.AddField(
            model_name='blog',
            name='describe',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='Описание статьи'),
        ),
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.URLField(blank=True, max_length=100, verbose_name='Сайт для статьи'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
