# Generated by Django 4.0.4 on 2022-07-21 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0011_alter_instslider_options_remove_blog_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='price_list/%Y/%m/%d/', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Прайс категории',
                'verbose_name_plural': 'Прайс категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('price_cats', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='photographer.pricecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-лист',
                'ordering': ['id'],
            },
        ),
    ]
