# Generated by Django 4.0.4 on 2022-08-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0013_remove_promo_photo1_remove_promo_photo2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='photo',
        ),
    ]
